### ISSUE TITLE
This error right here

### ISSUE THREAD

**Issue by Daijinryuu** [deluvsushi/AminoMssBoV2#2]
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/AminoMssBoV2/AminoMssBoV2.py", line 1, in <module>
    import amino
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/amino/__init__.py", line 9, in <module>
    from .sub_client import SubClient
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/amino/sub_client.py", line 13, in <module>
    from json_minify import json_minify
ModuleNotFoundError: No module named 'json_minify'

**Comment by deluvsushi** [comment]
pip install json_minify
